// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  posts: create.doc("posts", {"adding-likes-to-static-site.mdx": () => import("../src/content/writing/adding-likes-to-static-site.mdx?collection=posts"), "animated-tabs.mdx": () => import("../src/content/writing/animated-tabs.mdx?collection=posts"), "astro-fonts-api-optimization.mdx": () => import("../src/content/writing/astro-fonts-api-optimization.mdx?collection=posts"), "build-your-own-react-router.mdx": () => import("../src/content/writing/build-your-own-react-router.mdx?collection=posts"), "custom-code-blocks-astro-mdx.mdx": () => import("../src/content/writing/custom-code-blocks-astro-mdx.mdx?collection=posts"), "flip-dot-matrix.mdx": () => import("../src/content/writing/flip-dot-matrix.mdx?collection=posts"), "how-shadcn-documentation-is-built.mdx": () => import("../src/content/writing/how-shadcn-documentation-is-built.mdx?collection=posts"), "mise-as-nvm-replacement.mdx": () => import("../src/content/writing/mise-as-nvm-replacement.mdx?collection=posts"), "powershell-custom-prompt-setup.mdx": () => import("../src/content/writing/powershell-custom-prompt-setup.mdx?collection=posts"), "scratch-card.mdx": () => import("../src/content/writing/scratch-card.mdx?collection=posts"), "sparkling-text.mdx": () => import("../src/content/writing/sparkling-text.mdx?collection=posts"), "spotify-filters.mdx": () => import("../src/content/writing/spotify-filters.mdx?collection=posts"), "terminal-setup-2025.mdx": () => import("../src/content/writing/terminal-setup-2025.mdx?collection=posts"), "understanding-react-server-components.mdx": () => import("../src/content/writing/understanding-react-server-components.mdx?collection=posts"), "upload-images-with-rails-and-cloudinary.mdx": () => import("../src/content/writing/upload-images-with-rails-and-cloudinary.mdx?collection=posts"), "vercel-relative-time-card.mdx": () => import("../src/content/writing/vercel-relative-time-card.mdx?collection=posts"), }),
};
export default browserCollections;